version: "3.8"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apivendas-APP
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: ./.docker/postgres
    container_name: apivendas-DB
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apivendas

  redis:
    image: 'bitnami/redis:latest'
    container_name: apivendas-REDIS
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  pgadmin:
    image: dpage/pgadmin4
    container_name: apivendas-PGADMIN
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db

